### ISSUE TITLE
thinkpad t480s 报错

### ISSUE THREAD

**Issue by Qicloud-W** [rponeawa/thermalmonitordDisabler#5]
Traceback (most recent call last):
  File "pymobiledevice3\usbmux.py", line 167, in create_usbmux_socket
  File "pymobiledevice3\usbmux.py", line 111, in __init__
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui_app.py", line 311, in <module>
  File "gui_app.py", line 80, in __init__
  File "gui_app.py", line 161, in get_device_info
  File "pymobiledevice3\usbmux.py", line 414, in list_devices
  File "pymobiledevice3\usbmux.py", line 410, in create_mux
  File "pymobiledevice3\usbmux.py", line 174, in create
  File "pymobiledevice3\usbmux.py", line 169, in create_usbmux_socket
pymobiledevice3.exceptions.ConnectionFailedToUsbmuxdError

**Comment by rponeawa** [comment]
安装 iTunes，Apple 设备或爱思助手并连接手机后重新运行工具

**Comment by Qicloud-W** [comment]
搞定了
